energy_vector/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    url(r'^', include("main.urls")),
    url(r'^news/', include("news.urls")),
	url(r'^company/', include("company.urls")),
	url(r'^catalog/', include("catalog.urls")),
    url(r'^services/', include("services.urls")),
    url(r'^imagepool/', include("imagepool.urls")),

    url(r'^admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
# coding=utf-8
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'main'
urlpatterns = [

	url(r'^$', views.MainPageView.as_view(), name='main_page',),

	url(r'^call_order/$', views.CallorderFormView.as_view(),   name='call_order',),

	url(r'^order/(?P<serv_type>maintenance|repair)/(?P<equip_type>dgu|ups)/$',
						views.ServiceOrderFormView.as_view(),   name='service_order1',),

	url(r'^login/', auth_views.login,
		{"template_name":"end_templates/login.html"}, name='login'),
	url(r'^logout/', auth_views.logout, name='logout'),

]

news/urls.py
from django.conf.urls import url

from news.views import NewListView, NewDetailView, NewCreate, NewUpdate, NewDelete

app_name = 'news'
urlpatterns = [
	url(r'^$', NewListView.as_view(), name = "news_index"),
	url(r'^(?P<pk>\d+)/detail/$', NewDetailView.as_view(), name = "news_detail"),
	url(r'^add/$', NewCreate.as_view(), name = "news_add"),
	url(r'^(?P<pk>\d+)/edit/$', NewUpdate.as_view(), name = "news_edit"),
	url(r'^(?P<pk>\d+)/delete/$', NewDelete.as_view(), name = "news_delete"),
	]

news/models.py
# coding=utf-8
from __future__ import unicode_literals

from django.db import models
from django.utils.safestring import mark_safe

# Create your models here.
from taggit.managers import TaggableManager
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from precise_bbcode.fields import BBCodeTextField

from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from markdown_deux import markdown


class New(models.Model):
    title = models.CharField(max_length = 100,
        unique_for_date = 'publish',
        verbose_name = "Заголовок"
    )   
    image = ProcessedImageField(verbose_name = 'Картинка',
        help_text = "Будет лучше загрузить landscape фото ",
        upload_to='new_image',
        processors= [ResizeToFill(750,500)],
        format='JPEG',
        options={'quality': 60},
        blank = True,
        null = True,
    )
    content = models.TextField('Содержание')
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False, blank = True, null = True, default = None)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    # is_commentable = models.BooleanField(default = True, verbose_name = "Разрешены комментарии")
    # tags = TaggableManager(blank = True, verbose_name = "Теги")
    # user = models.ForeinKey(User, editable = False)


    class Meta:
        ordering = ["-timestamp", "-updated"]
        verbose_name = "Новостная статья"
        verbose_name_plural = "Новостные статьи"


    def __unicode__(self):
        return self.title


    def get_absolute_url(self):
        return reverse("news:news_detail", kwargs = {'pk': self.pk})


    def get_markdown(self):
        content = self.content
        markdown_content = markdown(content)
        return mark_safe(markdown_content)


    def delete(self, *args, **kwargs):
        self.image.delete(save = False)
        super(New, self).delete(*args, **kwargs)


# from django.contrib.comments.moderation import CommentModerator, moderator

# class NewsModerator(CommentModerator):
#   email_notification = True
#   enable_field = 'is_commentable'
    
# moderator.register(News,NewsModerator)


        

news/forms.py
from django import forms

from pagedown.widgets import PagedownWidget
from .models import New

class NewsForm(forms.ModelForm):
    content = forms.CharField(widget = PagedownWidget(show_preview = False))
    publish = forms.DateField(widget = forms.SelectDateWidget)
    class Meta:
        model = New
        fields = [
            "title",
            "content",
            "image",
            "draft",
            "publish",
        ]

news/views.py
# coding=utf-8
from django.shortcuts import render

# Create your views here.
from django.views.generic.dates import ArchiveIndexView
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy, reverse
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages

from news.models import New
from .forms import NewsForm
from generic.mixins import GensetengineListMixin, PageNumberMixin
from generic.controllers import PageNumberView


class NewListView(ListView, GensetengineListMixin):
    model = New
    template_name = "news/new_list.html"
    paginate_by = 2


class NewDetailView(DetailView, PageNumberMixin):
    model = New
    template_name = "news/new_detail.html"


class NewCreate(SuccessMessageMixin, CreateView, GensetengineListMixin):
    model = New
    success_message = "Новость успешно добавлена"
    form_class = NewsForm
    # def form_valid(self, form):
    #   output = super(NewCreate, self).form_valid(form)
    #   if MailList.objects.exists():
    #       s = "На сайте 'Веник-Торг' появилась новость:\n\n" + form.instance.title + "\n\n" + form.instance.description + "\n\nhttp://localhost:8000" + reverse("news_detail", kwargs = {"pk": form.instance.pk})
    #       letters = []

    #   for maillist_item in MailList.objects.all():
    #       letters = letters + [("Уведомление с сайта 'Веник-Торг'", "Здравствуйте, " + maillist_item.username + "!\n\n" + s, settings.DEFAULT_FROM_EMAIL, [maillist_item.email])]
    #       send_mass_mail(letters, fail_silently = True)
    #   return output


class NewUpdate(SuccessMessageMixin,  UpdateView):
    model = New
    success_message = "Новость успешно изменена"
    form_class = NewsForm


class NewDelete(PageNumberView, DeleteView, PageNumberMixin):
    model = New
    template_name = "news/new_conform_delete.html"
    success_url = reverse_lazy("news:news_index")


    def post(self, request, *args, **kwargs):
        messages.add_message(request, messages.SUCCESS, "Новость успешно удалена")
        return super(NewDelete, self).post(request, *args, **kwargs)

news/templates/news/new_conform_delete.html
{% extends "common/__l_single_col.html" %}

{% load bbcode_tags %}
{% block content %}

<div class = 'container post-detail-item'>
<br>
	<div class="row">
		<div class="col-sm-12 col-md-8 col-md-offset-2 post-detail-item">
			<h2>Вы действительно хотите удалить эту статью?</h2>
			<h1>{{ object.title }}</h1>
			<div>{{ object.get_markdown }}</div>
			<p class="posted">{{ object.posted|date:"j.m.Y H:i:s" }}</p>
			<form action="" method="POST">
				{% csrf_token %}
				<input class="btn btn-warning" type="submit" action="" value="Да, удалить." />
				<a class="btn btn-default" href="{% url "news:news_index" %}?page={{ pn }}" role="button">Нет, оставить.</a>
			</form>			
		</div>
	</div>	
</div>
{% endblock %}

news/templates/news/new_detail.html
{% extends "common/__l_single_col.html" %}
{% load bbcode_tags %}

{% block title %}
	{{ block.super }}
	{{ object.title }}
{% endblock %}


{% block content %}
	<div class="container">
		<div class='col-sm-12 col-md-8 col-md-offset-2 post-detail-item'>
			<h1><small>{{ object.title|upper }}</small></h1 >
			<p class="new"><small><em>{{ object.timestamp|date:"j.m.Y H:i:s" }}</em></small></p>	
			{% if object.image %}<img class = "img-responsive" src="{{ object.image.url }}"/>{% endif %}					
			{{ object.get_markdown }}
			<p><a href="{% url 'news:news_index' %}?page={{ pn }}">Назад</a></p>
		</div>
	</div>	
{% endblock %}

news/templates/news/new_form.html
{% extends "common/__l_single_col.html" %}
{% load staticfiles %}

{% load bootstrap %}

{% block title %}
  {{ block.super }}
  Добавление новости
{% endblock %}

{% block javascript %}
  {{ block.super }}	
	<script src="{% static "js/imagepool.js" %}" type="text/javascript"></script>
  
{% endblock %}

{% block head-extra %}
  {{ form.media }}
{% endblock head-extra %}

{% block content%}

<div class = 'container'>
  <div class="row">
    <div class="col-sm-6 new-preview post-detail-item">
      <h4 class="lead">ПРЕДВАРИТЕЛЬНЫЙ ПРОСМОТР</h4>
      <hr>
      <h3 id="preview-title"></h3>
      <p id="preview-content"></p>
    </div>
    <div class="col-sm-6">
       <div class="my-form-header">
          <a href="{% url "news:news_index" %}" type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a>
          <h4 class="lead">ФОРМА ДЛЯ ЗАПОЛНЕНИЯ</h4>
        </div>
        <hr>
          <form  action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form.as_p }}   
            <div class="my-form-footer">
            <a href="{% url "news:news_index" %}" type="button" class="btn btn-default">ЗАКРЫТЬ</a>
            <button type="submit" class="btn btn-success">СОХРАНИТЬ</button>
            </div>
          </form>
    </div>
  </div>
</div>


{% endblock %}

news/templates/news/new_list.html
{% extends "common/__l_single_col.html" %}
{% load staticfiles %}

{% block title %}
  {{ block.super }}
  Новости
{% endblock %}

{% block content %}
  {% include "includes/_messages.html" %}
<div class = 'container news'>
<br>
  <div class="row">
    <div class="col-md-12">
      {% if perms.news.add_new %}
        <p><a href="{% url "news:news_add" %}"><span class="glyphicon glyphicon-plus">добавить новость</span></a></p>
      {% endif %}
      </div>
  </div>
<div class="row">
  <div class="col-md-12">
     <h3 class="text-success"><b>НОВОСТИ КОМПАНИИ</b></h3>
  </div> 
</div>

<div class="row">
  {% for obj in object_list %} 
    <div class="col-sm-6 post-detail-item" >
      <div class="thumbnail ">
          {% if obj.image %}
           <img src='{{ obj.image.url }}' class='img-responsive' />
          {% endif %}
        <div class="caption post-detail-item">
          {% if obj.draft %}<h3>Staff only: Draft</h3>{% endif %} {% if obj.publish > today %}<h3>Staff Only: Future Post</h3>{% endif %}
          <h1><a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a> <small>{{ obj.publish }}</small></h1>
          <!-- {% if obj.user.get_full_name %}<p>Author: {{ obj.user.get_full_name }}</p>{% endif %} -->
          {{ obj.get_markdown|truncatewords_html:2 }}
          <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">Читать</a></p>
        </div>
      </div>
      <p class="buttons bottom-indent">
        {% if perms.news.change_new %}
        <a href="{% url 'news:news_edit' pk=obj.id %}?page={{ page_obj.number }}">Изменить</a>
        {% endif %}
        {% if perms.news.delete_new %}
        <a href="{% url 'news:news_delete' pk=obj.id %}?page={{ page_obj.number }}">Удалить</a>
        {% endif %}
      </p>
    </div>
  {% cycle '' '</div><div class="row">' %}
  {% endfor %}
</div>
 
  {% include "includes/_pagination.html" %}
</div>
{% endblock %}