company/urls.py
# coding=utf-8
from django.conf.urls import url
from . import views 


app_name = 'company'
urlpatterns = [

    url(r'^sro/$', views.SroView.as_view(), name='sro',),

    url(r'^certificates/$', views.CertificateList.as_view(), name='certificates'),

    url(r'^certificates_new/$', views.certificates_new, name='certificates_new'),
    url(r'^certificate_list_del/$', views.certificate_list_del, name='certificate_list_del'),


    url(r'^otzivi/$', views.OtzivList.as_view(), name='otzivi'),
    url(r'^otzivi_new/$', views.otziv_new, name='otziv_new'),
    url(r'^otziv_corr/$', views.OtzivCorr.as_view(), name='otziv_corr'),
    url(r'^otziv_corr/(?P<otziv_id>\d+)/$', views.otziv_corr_detail, name='otziv_corr_detail'),
    url(r'^otziv_del/$', views.otziv_list_del, name='otziv_del'),

    url(r'^documents/$', views.DocumentsView.as_view(),),

    url(r'^contacts/$', views.ContactsView.as_view(),),

]

energy_vector/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    url(r'^', include("main.urls")),
    url(r'^news/', include("news.urls")),
	url(r'^company/', include("company.urls")),
	url(r'^catalog/', include("catalog.urls")),
    url(r'^services/', include("services.urls")),
    url(r'^imagepool/', include("imagepool.urls")),

    url(r'^admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
# coding=utf-8
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'main'
urlpatterns = [

	url(r'^$', views.MainPageView.as_view(), name='main_page',),

	url(r'^call_order/$', views.CallorderFormView.as_view(),   name='call_order',),

	url(r'^order/(?P<serv_type>maintenance|repair)/(?P<equip_type>dgu|ups)/$',
						views.ServiceOrderFormView.as_view(),   name='service_order1',),

	url(r'^login/', auth_views.login,
		{"template_name":"end_templates/login.html"}, name='login'),
	url(r'^logout/', auth_views.logout, name='logout'),

]

company/models.py
# coding=utf-8
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
import datetime
import PIL
import os.path
from energy_vector.settings import BASE_DIR
from django.core.files import File
import os
import StringIO
from django.core.files.uploadedfile import InMemoryUploadedFile

from . widgets import PhoneField


def img_convert(img_file_path, size):
	"""
	берется полный путь к файлу изображению и кортеж типа size=(((260,355),'_1x'),((582,800),'_2x'),)
	из которого можно узнать сколько, каких размеров и с какими именами будут получены новые файлы 
	из исходного файла
	возвращается list из django_like_files JPG
	"""
	head,tail = os.path.split(img_file_path)

	fil, ext = os.path.splitext(tail)

	right_ext = ('.jpg','.jpeg','.JPG','.JPEG')
	# создаем PIL объект:
	img = PIL.Image.open(img_file_path)
	new_path=None
	# Если для загрузки выбран файл не в JPG формате, преобразуем его в JPG:	
	if not ext in right_ext:		
		new_path=BASE_DIR+'/tmp/'+unicode(fil)+'.jpeg'
		
		# конвертируем в JPEG:
		img.save(new_path)
		# создаем PIL объект в JPG формате:
		img = PIL.Image.open(new_path)
	
	# Если загруженный файл в JPG формате:
	
	# сюда будем сохранять django_like_files JPG нужных размеров:
	django_like_files=[]

		# size=(((260,355),'_1x'),((582,800),'_2x'),)
		
	for item in size:
		# делаем копию нашего исходного PIL объекта:
		foto_copy=img.copy()
		
		# преобразуем с помощю PIL в нужный формат
		foto_copy.thumbnail(item[0], PIL.Image.ANTIALIAS)
		
		# создаем объект StringIO -
		foto_copy_io = StringIO.StringIO()
		# запоминаем в него наш PIlовский foto_copy
		foto_copy.save(foto_copy_io, format='JPEG')
		
		#  создаем new Django file-like object, чтобы впоследствии запомнить его в 
		# ImageFild поле модели

		foto_copy_file = InMemoryUploadedFile(foto_copy_io, None, fil+item[1]+'.jpeg', 'image/jpeg',
                              foto_copy_io.len, None)				

		django_like_files.append(foto_copy_file)
	if new_path:
		
		os.remove(new_path)
	return django_like_files


# Create your models here.
class Marka(models.Model):
	marka = models.CharField(max_length=10,unique=True)
	

	def __unicode__(self):
		return self.marka


class Certificate(models.Model):
	# marka = models.ForeignKey(Marka, 
	# 	verbose_name = u'Выберите из списка или введите новое название марки:',
	# 	on_delete=models.CASCADE,null=True,default=None,)
	certificate = models.ImageField(u'Выберите файл в формате .jpg или .jpeg',
		upload_to = 'certificates')
	certificate_1x = models.ImageField(null=True,default=None,
		upload_to = 'certificates')
	certificate_2x = models.ImageField(null=True,default=None,
		upload_to = 'certificates')


	def __unicode__(self):
		return self.certificate.name

	def save(self,*args,**kwargs):
		try:
			this_record=Certificate.objects.get(id=self.id)
			if this_record.certificate !=self.certificate:
				this_record.certificate.delete(save=False)
		except:
			pass
		super(Certificate,self).save(*args,**kwargs)

	def delete(self,*args,**kwargs):
		self.certificate.delete(save=False)
		self.certificate_1x.delete(save=False)
		self.certificate_2x.delete(save=False)
		
		super(Certificate,self).delete(*args,**kwargs)

	def certificate_1x_2x(self):
		
		path = self.certificate.path
		size=(((260,355),'_1x'),((582,800),'_2x'),)
		
		# django_like_files - list с двумя Django file-like objects
		django_like_files = img_convert(path, size)
		
		self.certificate_1x=django_like_files[0]
		
		self.certificate_2x=django_like_files[1]
		
class Otziv(models.Model):

	otziv = models.ImageField(help_text='PDF не поддерживается!',upload_to = 'otziv',)
	
	otziv_1x = models.ImageField(null=True,default=None,upload_to = 'otziv',)
	
	otziv_2x = models.ImageField(null=True,default=None,upload_to = 'otziv',)

	text = models.TextField(verbose_name=u'НАБЕРИТЕ КРАТКО ТЕКСТ ОТЗЫВА',
		blank=True, null=True, default=None, max_length=1000,)
	

	def __unicode__(self):
		return self.otziv.name

	def save(self,*args,**kwargs):
		try:
			this_record=Otziv.objects.get(id=self.id)
			if this_record.otziv !=self.otziv:
				this_record.otziv.delete(save=False)
		except:
			pass
		super(Otziv,self).save(*args,**kwargs)

	def delete(self,*args,**kwargs):
		self.otziv.delete(save=False)
		self.otziv_1x.delete(save=False)
		self.otziv_2x.delete(save=False)
		
		super(Otziv,self).delete(*args,**kwargs)

	def otziv_1x_2x(self):
		path = self.otziv.path
		
		size=(((260,355),'_1x'),((582,800),'_2x'),)
		
		# django_like_files - list с двумя Django file-like objects
		django_like_files = img_convert(path, size)
		
		self.otziv_1x=django_like_files[0]
		self.otziv_2x=django_like_files[1]


class Callorderuser(models.Model):

	name = models.CharField(u'ИМЯ',max_length=20,) 
	phone = PhoneField(code_length = 3, num_length = 7)
	text = models.CharField(u'ВОПРОС',max_length=200,)

	published_date = models.DateField()

	

		

company/forms.py
# coding=utf-8
from django import forms

from .widgets import MultiFileInput, PhoneField
from .models import Callorderuser, Marka, Certificate, Otziv
# from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User

from django.core.exceptions import ValidationError

# def validate_images_format(file_instance):

# 	if file_instance.content_type=='image/jpeg':
# 		print 'file_instance.content_type=',file_instance.content_type
		
# 		raise ValidationError("Файл в 'jpeg' формате нельзя загрузить на сайт!")


class CertificateForm(forms.Form):

	certificate = forms.ImageField(label=u'', widget = MultiFileInput,
					# validators = [validate_images_format]
					)

class OtzivForm(forms.ModelForm):

	class Meta:
		model = Otziv
		fields = ['otziv','text']
		widgets = {
			'text':forms.widgets.Textarea()	
		}
			
		error_messages = {
            'name': {
                'max_length': "This writer's name is too long.",
            },
        }
			
class Callorder(forms.Form):

	name = forms.CharField(label=u'ВАШЕ ИМЯ',max_length = 20, initial = "ВАШЕ ИМЯ",)

	phone_number=forms.CharField(label = u'НОМЕР ТЕЛЕФОНА', max_length = 12, initial='+71234567890',)

	question = forms.CharField(label=u'ВОПРОС',max_length = 1000, 
		widget = forms.widgets.Textarea, initial = 'ЖЕЛАТЕЛЬНО УКАЗАТЬ', required = False )

company/views.py
# coding=utf-8
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponse, HttpResponseRedirect

from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator

from .models import Marka, Certificate, Otziv, Callorderuser
from catalog.models import Gensetengine
from services.models import Service
from .forms import CertificateForm, OtzivForm
from django.views.generic import ListView

from django.views.generic import TemplateView
from generic.mixins import GensetengineListMixin

import re


# Create your views here.
class DocumentsView(TemplateView, GensetengineListMixin):
	template_name="end_templates/in_the_development.html"

class SroView(TemplateView, GensetengineListMixin):
	template_name="company/sro.html"

class ContactsView(TemplateView, GensetengineListMixin):
	template_name="company/contacts.html"
				
class CertificateList(ListView, GensetengineListMixin):
	model = Certificate
	
class OtzivList(ListView, GensetengineListMixin):
	'''Выводится страница с отзывами о компании
	'''
	model = Otziv
	template_name = 'company/otziv_list.html'
	context_object_name = 'otzivs'

class OtzivCorr(ListView, GensetengineListMixin):
	'''
	выводится страница, где можно выбрать отзыв для корректировки
	'''
	model = Otziv
	template_name = 'company/otziv_list_corr.html'
	context_object_name = 'otzivs'

@permission_required('company.delete_otziv')
@login_required
def otziv_list_del(request):
	gensetengines = Gensetengine.objects.all()
	services = Service.objects.all()

	otzivs = Otziv.objects.all()
	do_choice=0
	
	if request.method =='POST':
		error=None
		for otziv in otzivs:
			if unicode(otziv.id) in request.POST:
				otziv.delete()
				do_choice=1
		if do_choice==1:
			return HttpResponseRedirect('/otzivi/')
		else:
			error=u'**Вы не выбрали не одного отзыва для удаления!'				
			return render(request, 'company/otziv_list_del.html',
					{'otzivs':otzivs, 'error':error, 
					'gensetengines':gensetengines,'services':services })
	else:
		return render(request, 'company/otziv_list_del.html',
			{'otzivs':otzivs, 'gensetengines':gensetengines,'services':services })


@permission_required('company.delete_certificate')
@login_required
def certificate_list_del(request):
	gensetengines = Gensetengine.objects.all()
	services = Service.objects.all()

	certificates = Certificate.objects.all()
	do_choice = 0

	if request.method =='POST':
		error=None
		for certificate in certificates:
			if unicode(certificate.id) in request.POST:				
				certificate.delete()
				do_choice=1
		if do_choice==1:
			return HttpResponseRedirect('/certificates/')
		else:
			error=u'**Вы не выбрали не одного сертификата для удаления!'				
			return render(request, 'company/certificate_list_del.html',
							{'certificates':certificates, 'error':error})
	else:
		return render(request, 'company/certificate_list_del.html',
			{'certificates':certificates, 'gensetengines':gensetengines})






@permission_required('company.add_certificate')
@login_required		
def certificates_new(request):
	gensetengines = Gensetengine.objects.all()
	services = Service.objects.all()

	# if this is a POST request we need to process the form data
	if request.method == 'POST':
		# create a form instance and populate it with data from the request:
		form = CertificateForm(request.POST, request.FILES)
		
		if form.is_valid():
		
			certificates = request.FILES
			
			i=len(certificates.getlist('certificate'))-1
			
			while i>=0:

				certificate = certificates.getlist('certificate')[i]
				
				c = Certificate( certificate = certificate)

				c.save()

				c.certificate_1x_2x()
				
				c.save()
				i=i-1			

			return HttpResponseRedirect('/certificates/')
    # if a GET (or any other method) we'll create a blank form
	else:
		form = CertificateForm()


	return render(request,  'company/certificates_new_form.html', {'form': form,
					    	'title':'выберите файлы с сертификатами',
					    	'value':'добавить',
					    	'enctype_atr':'multipart/form-data',
					    	'gensetengines':gensetengines,
					    	'services':services 
					    	})




@permission_required('company.add_otziv')
@login_required		
def otziv_new(request):
	gensetengines = Gensetengine.objects.all()
	services = Service.objects.all()

	# if this is a POST request we need to process the form data
	if request.method == 'POST':
        # create a form instance and populate it with data from the request:
		form = OtzivForm(request.POST,request.FILES)
		
		if form.is_valid():
			# process the data in form.cleaned_data as required
			
			t = form.cleaned_data['text']
			# t_list=re.split(r'\n+',t)
			# text='*|*'.join(t_list)

			otziv = request.FILES['otziv']
			print 'otziv=',otziv	
			o = Otziv(text = t, otziv = otziv)

			o.save()

			o.otziv_1x_2x()
			
			o.save()		

			return HttpResponseRedirect('/otzivi/')
    # if a GET (or any other method) we'll create a blank form
	else:
		form = OtzivForm()


	return render(request,  'company/otziv_new_form.html', {'form': form,
					    		'enctype_atr':'multipart/form-data',
					    		'gensetengines':gensetengines,
					    		'services':services 
					    	})


@permission_required('company.add_otziv')
@login_required		
def otziv_corr_detail(request,otziv_id):
	'''
	корректировка одного отзыва
	'''
	gensetengines = Gensetengine.objects.all()
	services = Service.objects.all()

	otziv=get_object_or_404(Otziv,pk=otziv_id)
	
	if request.method =='POST':

		form=OtzivForm(request.POST,request.FILES, instance=otziv)

		if form.is_valid():
			form.cleaned_data
			form.save()
			
			o=get_object_or_404(Otziv,pk=otziv_id)
			o.otziv_1x_2x()	
			o.save()

		return HttpResponseRedirect('/otzivi/')	

	else:
		form = OtzivForm(instance=otziv)

	return render(request, 'company/otziv_corr_detail.html',
						{'form':form,'gensetengines':gensetengines,
						'services':services })	

company/templates/company/certificate_list.html
{% extends "common/__l_single_col.html" %}
{% load staticfiles %}

{% block stylesheet %}
	{{ block.super }}
	<link rel="stylesheet" type="text/css" href="{% static 'mosaicflow/mosaicflow.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'fancybox/jquery.fancybox.css' %}">
{% endblock %}

{% block content %}
<br>
<div class="container">
	<div class="row">
		{% if user.is_authenticated %}
		  {% if perms.company.add_certificate %}
		<div class="col-sm-3"><a class='certificate-menu' href="{% url 'company:certificates_new' %}" title="добавить сертификаты"><span class="glyphicon glyphicon-plus">добавить сертификаты</span></a></div>
			{% endif %}
			{% if object_list %}
				{% if perms.company.add_certificate %}
		<div class="col-sm-3"><a class='certificate-menu' href="{% url 'company:certificate_list_del' %}" title="удалить сертификаты"><span class="glyphicon glyphicon-minus">удалить сертификаты</span></a></div>
				{% endif %}
			{% endif %}
		{% endif %}	
	</div>

	<br>
	<div class="clearfix mosaicflow">
		{% for item in object_list %}
		{% comment %}
		<div class="mosaicflow__item">
			<a class="fancyimage" data-fancybox-group="group" title="{{item.certificate}}" href="{{item.certificate_2x.url}}">
				<img src="{{item.certificate_1x.url}}" alt="">
			</a>
		</div>
		{% endcomment %}
		<img src="{{item.certificate_1x.url}}" alt="">
		{% endfor %}

	</div>
</div>
{% endblock %}

{% block javascript %}
	{{ block.super }}
	<script type="text/javascript" src = "{% static 'fancybox/jquery.fancybox.pack.js' %}"></script>
	<script src="{% static 'mosaicflow/jquery.mosaicflow.min.js' %}"></script>	
	<script type="text/javascript" src = "{% static 'js/certificate.js' %}"></script>
{% endblock %}

company/templates/company/certificate_list_del.html
{% extends "common/__l_single_col.html" %}
{% load staticfiles %}

{% block stylesheet %}
	{{ block.super }}
	<link rel="stylesheet" type="text/css" href="{% static 'mosaicflow/mosaicflow.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'fancybox/jquery.fancybox.css' %}">
{% endblock %}

{% block content %}
<br>
<form action="{% url 'company:certificate_list_del'%}" method="POST">
	{% csrf_token %}
	<div class="container">
		<div class="row">
			<div class="col-sm-4 col-sm-12">
				<input type='submit' value="удалить выбранное">
			</div>
		</div>
		<div class="row">
			<div class="col-sm-4 col-sm-12">
				<p ><strong>{{error}}</strong></p>
			</div>
		</div>

		<br>
		<div class="clearfix mosaicflow">
			{% for certificate in certificates %}
			
			<div class="mosaicflow__item">
				<input type="checkbox" name='{{certificate.id}}'>
				<a class="fancyimage" data-fancybox-group="group" title="{{certificate.certificate}}" href="{{item.certificate_2x.url}}">
					<img src="{{certificate.certificate_1x.url}}" alt="">
				</a>
			</div>
			{% endfor %}

		</div>
	</div>
{% endblock %}

{% block javascript %}
	{{ block.super }}
	<script type="text/javascript" src = "{% static 'fancybox/jquery.fancybox.pack.js' %}"></script>
	<script src="{% static 'mosaicflow/jquery.mosaicflow.min.js' %}"></script>	
	<script type="text/javascript" src = "{% static 'js/certificate.js' %}"></script>
{% endblock %}

company/templates/company/certificates_new_form.html
{% extends "common/__l_single_col.html" %}

{% block content %}
<br>
<div class='form'>
	<div class="enter-container grey-form-block">	
		<h4 class="text-center">ДОБАВЬТЕ НОВЫЕ СЕРТИФИКАТЫ</h4>		
		<a href="{% url 'company:certificates' %}" type="button" class='close'><span >&times;</span></a>		
	</div>
	
	<form enctype="multipart/form-data" action="{% url 'company:certificates_new' %}" method="post">
		{% csrf_token %}
			<p class="text-center">Можно загрузить: JPEG,PNG,GIF,TIF</p>
			<p class="text-center"><b>PDF НЕ ПОДДЕРЖИВАЕТСЯ!</b></p>
		
		<div class="enter-container ">	
			{{ form.as_p}}

		</div>
					
		<div class="button-container text-center grey-form-block">
			
				<input class="btn btn-default" type="submit" value="ДОБАВИТЬ">
			
		<!-- <input type="hidden" name="next" value="{{ next }}"> -->
		</div>
	</form>
</div>

{% endblock %}

company/templates/company/otziv_corr.html
{% extends "common/__l_single_col.html" %}

{% block content %}

<div class='form'>
	<div class="enter-container grey-form-block">
		<a href="{% url 'company:otzivi' %}" type="button" class='close'><span >&times;</span></a>	
		<h4 class="text-center">КОРРЕКТИРОВКА ОТЗЫВА</h4>		
				
	</div>
	
	
	<form action="" method="post" enctype="multipart/form-data" >
		<div class="enter-container text-center">
			{% csrf_token %}
		

		<div>	
			{{ form.as_p}}

		</div>
	</div>
		<div class="button-container text-center grey-form-block">
			
			<input class="btn btn-default" type="submit" value="КОРРЕКТИРОВАТЬ">
			
		</div>
	</form>
</div>

{% endblock %}

company/templates/company/otziv_corr_detail.html
{% extends "common/__l_single_col.html" %}

{% block content %}

<div class='form'>
	<div class="enter-container grey-form-block">
		<a href="{% url 'company:otzivi' %}" type="button" class='close'><span >&times;</span></a>	
		<h4 class="text-center">КОРРЕКТИРОВКА ОТЗЫВА</h4>		
				
	</div>
	
	
	<form action="" method="post" enctype="multipart/form-data" >
		<div class="enter-container text-center">
			{% csrf_token %}
		

		<div>	
			{{ form.as_p}}

		</div>
	</div>
		<div class="button-container text-center grey-form-block">
			
			<input class="btn btn-default" type="submit" value="КОРРЕКТИРОВАТЬ">
			
		</div>
	</form>
</div>

{% endblock %}

company/templates/company/otziv_list.html
{% extends "common/__l_single_col.html" %}
{% load staticfiles %}
{% load bbcode_tags %}

{% block stylesheet %}
	{{ block.super }}
	
	<link rel="stylesheet" type="text/css" href="{% static 'fancybox/jquery.fancybox.css' %}">
{% endblock %}

{% block content %}
<br>
<div class="container">
	<div class="row">
{% if user.is_authenticated %}
  {% if perms.company.add_otziv %}
			<div class="col-sm-4 col-sm-12"><a  href="{% url 'company:otziv_new' %}" title="добавить сертификаты"><span class="glyphicon glyphicon-plus">добавить новый отзыв</span></a></div>
		{% if otzivs and otzivs|length_is:"1" %}
			<div class="col-sm-4 col-sm-12"><a  href="{% url 'company:otziv_corr_detail' otzivs.0.id %}" title="добавить сертификаты"><span class="glyphicon glyphicon-plus">корректировать отзыв</span></a></div>
			<div class="col-sm-4 col-sm-12"><a  href="{% url 'company:otziv_del' %}" title="добавить сертификаты"><span class="glyphicon glyphicon-plus">удалить отзывы</span></a></div>		
		{% elif otzivs %}	
			<div class="col-sm-4 col-sm-12"><a  href="{% url 'company:otziv_corr' %}" title="добавить сертификаты"><span class="glyphicon glyphicon-plus">корректировать отзыв</span></a></div>
			<div class="col-sm-4 col-sm-12"><a  href="{% url 'company:otziv_del' %}" title="добавить сертификаты"><span class="glyphicon glyphicon-plus">удалить отзывы</span></a></div>
		{% endif %}

		
	{% endif %}
{% endif %}	
	</div>

	<br>
	{% for otziv in otzivs %}
	<div class="row">	
		<div class="col-md-2 col-sm-12">
			<a class="fancyimage" data-fancybox-group="group" title="{{otziv.otziv}}" href="{{otziv.otziv_2x.url}}">
				<img class = 'otziv img-responsive' src="{{otziv.otziv_1x.url}}" alt="{{otziv.otziv}}" alt="{{otziv.text}}" />
			</a>
		</div>
		<div class="col-md-10 col-sm-12">
			<br>
			{% bbcode otziv.text %}		
		</div>
	</div>
	<br>
	{% endfor %}
</div>
{% endblock %}

{% block javascript %}
	{{ block.super }}
	<script type="text/javascript" src = "{% static 'fancybox/jquery.fancybox.pack.js' %}"></script>
	<script type="text/javascript" src = "{% static 'js/certificate.js' %}"></script>
{% endblock %}

company/templates/company/otziv_list_corr.html
{% extends "common/__l_single_col.html" %}
{% load staticfiles %}
{% load bbcode_tags %}

{% block stylesheet %}
	{{ block.super }}
	
	<link rel="stylesheet" type="text/css" href="{% static 'fancybox/jquery.fancybox.css' %}">
{% endblock %}

{% block content %}
<br>
<div class="container">
	<br>
	<div class="row">
		<div class="col-sm-4 col-sm-12"><a  href="{% url 'company:otziv_new' %}" title="добавить сертификаты"><span class="glyphicon glyphicon-chevron-left">вернуться</span></a></div>
		<div class="col-md-12 col-sm-12">
			<p class="text-center"><strong>Кликните на отзыв для корректировки</strong></p>
		</div>
	</div>
	<br>
	{% for otziv in otzivs %}
	<div class="row">	
		<div class="col-md-2 col-sm-12">
			<a title="{{otziv.otziv}}" href="{% url 'company:otziv_corr_detail' otziv.id %}">
				<img class = 'otziv img-responsive' src="{{otziv.otziv_1x.url}}" alt="{{otziv.otziv}}" alt="{{otziv.text}}" />
			</a>
		</div>
		<div class="col-md-10 col-sm-12">
			<br>
			{% bbcode otziv.text %}		
		</div>
	</div>
	<br>
	{% endfor %}
</div>
{% endblock %}

{% block javascript %}
	{{ block.super }}
	<script type="text/javascript" src = "{% static 'fancybox/jquery.fancybox.pack.js' %}"></script>
	<script type="text/javascript" src = "{% static 'js/certificate.js' %}"></script>
{% endblock %}

company/templates/company/otziv_list_del.html
{% extends "common/__l_single_col.html" %}
{% load staticfiles %}
{% load bbcode_tags %}

{% block stylesheet %}
	{{ block.super }}
	
	<link rel="stylesheet" type="text/css" href="{% static 'fancybox/jquery.fancybox.css' %}">
{% endblock %}

{% block content %}
<br>
<form action="{% url 'company:otziv_del'%}" method="POST">
	{% csrf_token %}
	<div class="container">
		<div class="row">			
			<div class="col-sm-4 col-sm-12">
				<input type='submit' value="удалить выбранное">
			</div>	
		</div>
		<div class="row">
			<div class="col-sm-4 col-sm-12">
				<p ><strong>{{error}}</strong></p>
			</div>
		</div>

		<br>
		{% for otziv in otzivs %}
		<div class="row">	
			<div class="col-md-2 col-sm-12">
				<input type="checkbox" name='{{otziv.id}}'>
				<img class = 'otziv img-responsive' src="{{otziv.otziv_1x.url}}" alt="{{otziv.otziv}}" alt="{{otziv.text}}" />
				
			</div>
			<div class="col-md-10 col-sm-12">
				<br>
				{% bbcode otziv.text %}		
			</div>
		</div>
		<br>
		{% endfor %}
	</div>
</form>


{% endblock %}

{% block javascript %}
	{{ block.super }}
	<script type="text/javascript" src = "{% static 'fancybox/jquery.fancybox.pack.js' %}"></script>
	<script type="text/javascript" src = "{% static 'js/certificate.js' %}"></script>
{% endblock %}

company/templates/company/otziv_new_form.html
{% extends "common/__l_single_col.html" %}

{% block content %}

<div class='form'>
	<div class="enter-container grey-form-block">
		<a href="{% url 'company:otzivi' %}" type="button" class='close'><span >&times;</span></a>	
		<h4 class="text-center">ДОБАВЬТЕ НОВЫЙ ОТЗЫВ</h4>		
				
	</div>
	
	
	<form enctype="{{enctype_atr}}" action="{{action_atr}}" method="post">
		<div class="enter-container text-center">
			{% csrf_token %}
		

		<div>	
			{{ form.as_p}}

		</div>
	</div>
		<div class="button-container text-center grey-form-block">
			
			<input class="btn btn-default" type="submit" value="ДОБАВИТЬ">
			
		<!-- <input type="hidden" name="next" value="{{ next }}"> -->
		</div>
	</form>
</div>

{% endblock %}