catalog/urls.py
# coding=utf-8
from django.conf.urls import url
from . import views


app_name = 'catalog'
urlpatterns = [

    url(r'^dgu/(?P<gensetengine_id>\d+)/$', views.GensetList.as_view(), 
						    	name='genset_list',),

    url(r'^dgu/(?P<gensetengine_id>\d+)/corr/$', views.GensetListCorr.as_view(), 
						    	name='genset_list_corr',),

	url(r'^dgu/(?P<gensetengine_id>\d+)/create/$', views.GensetCreate.as_view(), 
						    	name='genset_create',),

	url(r'^dgu/(?P<pk>\d+)/update/$', views.GensetUpdate.as_view(), 
						    	name='genset_update',),

	url(r'^dgu/(?P<pk>\d+)/delete/$', views.GensetDelete.as_view(), 
								name='genset_delete',),

	url(r'^dgu/gensetengine/corr/$', views.GensetengineListCorr.as_view(), 
						    	name='gensetengine_list_corr',),

	url(r'^dgu/gensetengine/create/$', views.GensetengineCreate.as_view(), 
						    	name='gensetengine_create',),

	url(r'^dgu/gensetengine/(?P<pk>\d+)/update/$', views.GensetengineUpdate.as_view(), 
						    	name='gensetengine_update',),

	url(r'^dgu/gensetengine/(?P<pk>\d+)/delete/$', views.GensetengineDelete.as_view(), 
								name='gensetengine_delete',),



]

energy_vector/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    url(r'^', include("main.urls")),
    url(r'^news/', include("news.urls")),
	url(r'^company/', include("company.urls")),
	url(r'^catalog/', include("catalog.urls")),
    url(r'^services/', include("services.urls")),
    url(r'^imagepool/', include("imagepool.urls")),

    url(r'^admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
# coding=utf-8
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'main'
urlpatterns = [

	url(r'^$', views.MainPageView.as_view(), name='main_page',),

	url(r'^call_order/$', views.CallorderFormView.as_view(),   name='call_order',),

	url(r'^order/(?P<serv_type>maintenance|repair)/(?P<equip_type>dgu|ups)/$',
						views.ServiceOrderFormView.as_view(),   name='service_order1',),

	url(r'^login/', auth_views.login,
		{"template_name":"end_templates/login.html"}, name='login'),
	url(r'^logout/', auth_views.logout, name='logout'),

]

catalog/models.py
# coding=utf-8
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Gensetengine(models.Model):
	engine = models.CharField(max_length = 20, unique = True,
			verbose_name = "Производитель двигателя ДГУ")
	logo = models.ImageField(verbose_name = "Логотип", 
			upload_to = 'catalog/dgu/logo', blank=True, null=True, default=None,)

	text = models.TextField(verbose_name = 'Текст, кот. будет выводиться перед ...',
			blank=True, null=True, default=None,)

	def __unicode__(self):
		return self.engine

	def save(self,*args,**kwargs):
		try:
			this_record=Gensetengine.logo.get(id=self.id)
			if this_record.logo !=self.logo:
				this_record.logo.delete(save=False)
		except:
			pass
		super(Gensetengine,self).save(*args,**kwargs)

	def delete(self,*args,**kwargs):
		self.logo.delete(save=False)		
		super(Gensetengine,self).delete(*args,**kwargs)

class Genset(models.Model):
	gensetengine = models.ForeignKey(Gensetengine,verbose_name = 'Марка двигателя')
	model = models.CharField(verbose_name = "Марка  дизельгенератора",
				max_length = 10, unique = True)
	stand_by_kva = models.DecimalField(verbose_name = "ESP(Stand-by)/кВА", max_digits=8, decimal_places=1)
	stand_by_kw = models.DecimalField(verbose_name = "ESP(Stand-by)/кВт", max_digits=8, decimal_places=1)
	prime_kva = models.DecimalField(verbose_name = "PRP(Prime)/кВА", max_digits=8, decimal_places=1)
	prime_kw = models.DecimalField(verbose_name = "PRP(Prime)/кВт", max_digits=8, decimal_places=1)
	
	engine_model = models.CharField(verbose_name = "Модель двигателя", max_length = 20)

	spec = models.FileField(verbose_name = "pdf файл спецификации",
		upload_to = 'catalog/dgu/spec_pdf', blank=True, null=True, default=None,)

	def __unicode__(self):
		return self.model

	def save(self,*args,**kwargs):
		try:
			this_record=Gensetspec.get(id=self.id)
			if this_record.spec !=self.spec:
				this_record.spec.delete(save=False)
		except:
			pass
		super(Genset,self).save(*args,**kwargs)

	def delete(self,*args,**kwargs):
		self.spec.delete(save=False)		
		super(Genset,self).delete(*args,**kwargs)

catalog/views.py
# coding=utf-8
from django.shortcuts import render
from .models import Genset, Gensetengine
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, ProcessFormView
from generic.mixins import GensetengineListMixin
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin

# Create your views here.



class GensetList(ListView, GensetengineListMixin):
	model = Genset
	template_name = 'catalog/gensetlist.html'
	context_object_name = 'gensets'
	def get_queryset(self):
		return Genset.objects.filter(gensetengine__id = self.kwargs['gensetengine_id'])
	def get_context_data(self, **kwargs):
		context = super(GensetList, self).get_context_data(**kwargs)
		context['gensetengine'] = Gensetengine.objects.get(pk=self.kwargs['gensetengine_id'])
		return context

class GensetListCorr(PermissionRequiredMixin, ListView, GensetengineListMixin):
	permission_required = ('genset.can_change', 'genset.can_delete')
	model = Genset
	template_name = 'catalog/gensetlistcorr.html'
	context_object_name = 'gensets'
	def get_queryset(self):
		return Genset.objects.filter(gensetengine__id = self.kwargs['gensetengine_id'])	
	def get_context_data(self, **kwargs):
		context = super(GensetListCorr, self).get_context_data(**kwargs)
		context['gensetengine'] = Gensetengine.objects.get(pk=self.kwargs['gensetengine_id'])
		return context

class GensetCreate(PermissionRequiredMixin, CreateView, GensetengineListMixin):
	permission_required = 'genset.can_add'
	model = Genset
	fields = '__all__'

	def post(self, request, *args, **kwargs):
		self.success_url = reverse_lazy('catalog:genset_list', kwargs= {'gensetengine_id':self.kwargs['gensetengine_id']})
		return super(GensetCreate, self).post(request, *args, **kwargs)
	def get_context_data(self, **kwargs):
		context = super(GensetCreate, self).get_context_data(**kwargs)
		context['gensetengine_pk'] = Gensetengine.objects.get(pk=self.kwargs['gensetengine_id']).pk
		return context



class GensetUpdate(PermissionRequiredMixin, UpdateView, GensetengineListMixin):
	permission_required = 'genset.can_change'
	model = Genset
	fields = '__all__'
	def post(self, request, *args, **kwargs):
		self.success_url = reverse_lazy('catalog:genset_list_corr',
			kwargs= {'gensetengine_id':Genset.objects.get(pk=self.kwargs['pk']).gensetengine.pk})
		return super(GensetUpdate, self).post(request, *args, **kwargs)
	def get_context_data(self, **kwargs):
		context = super(GensetUpdate, self).get_context_data(**kwargs)
		context['gensetengine_pk'] = Genset.objects.get(pk=self.kwargs['pk']).gensetengine.pk
		return context

class GensetDelete(PermissionRequiredMixin, DeleteView, GensetengineListMixin):
	permission_required = 'genset.can_delete'
	model = Genset
	def post(self, request, *args, **kwargs):
		self.success_url = reverse_lazy('catalog:genset_list_corr',
			kwargs= {'gensetengine_id':Genset.objects.get(pk=self.kwargs['pk']).gensetengine.pk})
		return super(GensetDelete, self).post(request, *args, **kwargs)
	def get_context_data(self, **kwargs):
		context = super(GensetDelete, self).get_context_data(**kwargs)
		context['gensetengine_pk'] = Genset.objects.get(pk=self.kwargs['pk']).gensetengine.pk
		return context

class GensetengineCreate(PermissionRequiredMixin, CreateView, GensetengineListMixin):
	permission_required = 'gensetengine.can_add'
	model = Gensetengine
	fields = '__all__'
	
	def post(self, request, *args, **kwargs):
		self.success_url = reverse_lazy('catalog:genset_list',
						kwargs= {'gensetengine_id': unicode(int(Gensetengine.objects.last().id)+1)})
		return super(GensetengineCreate, self).post(request, *args, **kwargs)

class GensetengineListCorr(PermissionRequiredMixin, ListView, GensetengineListMixin):
	permission_required = ('gensetengine.can_change', 'gensetengine.can_delete')
	model = Gensetengine
	template_name = 'catalog/gensetengine_listcorr.html'
	context_object_name = 'gensetengines'	
	def get_context_data(self, **kwargs):
		context = super(GensetengineListCorr, self).get_context_data(**kwargs)
		context['gensetengine_id'] = Gensetengine.objects.first().pk
		return context

	
class GensetengineUpdate(PermissionRequiredMixin, UpdateView, GensetengineListMixin):
	permission_required = 'gensetengine.can_change'
	model = Gensetengine
	fields = '__all__'
	success_url = reverse_lazy('catalog:gensetengine_list_corr')

class GensetengineDelete(PermissionRequiredMixin, DeleteView, GensetengineListMixin):
	permission_required = 'gensetengine.can_delete'
	model = Gensetengine
	success_url = reverse_lazy('catalog:gensetengine_list_corr')	

catalog/templates/catalog/genset_confirm_delete.html
{% extends "common/__l_single_col.html" %}
{% load staticfiles %}
{% block content %}

<div class = 'container'>
<br>
	<div class="row">
	<h2>Вы действительно хотите удалить эту строку?</h2>
		<br>
		<table class='table catalog table-bordered '>
			<tbody>
				<tr>
					<th rowspan="2">МОДЕЛЬ<br>ДГУ</th>
					<th colspan="2">ESP(Stand-by)</th>
					<th colspan="2">PRP(Prime)</th>
					<th rowspan="2">GOV</th>
					<th rowspan="2 specification">СПЕЦИФИКАЦИЯ</th>
				</tr>
				<tr>
					<th>кВА</th>
					<th>кВ</th>
					<th>кВА</th>
					<th>кВ</th>
				</tr>
				<tr>
					<td>{{genset.model}}</td>
					<td>{{genset.stand_by_kva}}</td>
					<td>{{genset.stand_by_kw}}</td>
					<td>{{genset.prime_kva}}</td>
					<td>{{genset.prime_kw}}</td>
					<td>{{genset.engine_model}}</td>
					<td><a href="#"><img src="{% static 'images/get_pdf.jpg' %} " alt='получить спецификацию'></a></td>
				</tr>
			</tbody>
		</table>
	</div>
	<div class="row">
		<div class="col-sm-2">
			<form action="" method="POST">
				{% csrf_token %}
				<input class="btn btn-warning" type="submit" action="" value="Да, удалить." />
			</form>
		</div>
		<div class="col-sm-2">
			<a class="btn btn-default" href="{% url 'catalog:genset_list_corr' gensetengine_pk %}" role="button">Нет, оставить.</a>
		</div>
	</div>	
</div>
{% endblock %}

catalog/templates/catalog/genset_form.html
{% extends "common/__l_single_col.html" %}

{% block content %}
<form  action="" method="post" enctype="multipart/form-data">
	<div class = 'container'>
	<br>
	<div class='row'>
		<div class="col-sm-12"><a class='certificate-menu' href="{% url 'catalog:genset_list' gensetengine_pk %}" title="вернуться"><span class="glyphicon glyphicon-menu-left">вернуться</span></a>
		</div>
	</div>
	<br>
	<div class='row'>
		<div class="col-sm-12">
			<span class="lead">
				{{form.gensetengine.label}}:
			</span>
			<span>
				{{form.gensetengine}}
				<a href="{% url 'catalog:gensetengine_create' %}" title="добавить марку, если нет в списке"><span class="glyphicon glyphicon-plus"></span></a>
				<a href="{% url 'catalog:gensetengine_list_corr' %}" title="редактировать базу марок двигателей" ><span class="glyphicon glyphicon-pencil"></span></a>
			</span>
		<div class="col-sm-12 text-danger">
			{{form.gensetengine.errors}}
		</div>	
		</div>		
	</div>

		<table class='table catalog table-bordered '>
			<tbody>
				<tr>
					<th rowspan="2">МОДЕЛЬ<br>ДГУ<br></th>
					<th colspan="2">ESP(Stand-by)</th>
					<th colspan="2">PRP(Prime)</th>
					<th rowspan="2">МОДЕЛЬ<br>ДВИГАТЕЛЯ<br></th>
					<th rowspan="2 specification">СПЕЦИФИКАЦИЯ</th>
				</tr>
				<tr>
					<th>кВА</th>
					<th>кВ</th>
					<th>кВА</th>
					<th>кВ</th>
				</tr>
				<tr>{% csrf_token %}
					<td>{{form.model}}</td>
					<td>{{form.stand_by_kva}}</td>
					<td>{{form.stand_by_kw}}</td>
					<td>{{form.prime_kva}}</td>
					<td>{{form.prime_kw}}</td>
					<td>{{form.engine_model}}</td>
					<td>{{form.spec}}</td>
				</tr>
				{% if form.model.errors or form.stand_by_kva.errors or form.stand_by_kw.errors or form.prime_kva.errors or form.prime_kw.errors or form.engine_model.errors or form.spec.errors %}
				<tr>
					<td class="text-danger last">{{form.model.errors}}</td>
					<td class="text-danger last">{{form.stand_by_kva.errors}}</td>
					<td class="text-danger last">{{form.stand_by_kw.errors}}</td>
					<td class="text-danger last">{{form.prime_kva.errors}}</td>
					<td class="text-danger last">{{form.prime_kw.errors}}</td>
					<td class="text-danger last">{{form.engine_model.errors}}</td>
					<td class="text-danger last">{{form.spec.errors}}</td>
				</tr>
				{% endif %}
			</tbody>
		</table>
		
		<input class="btn btn-default" type="submit" value="Добавить">
	</div>
</form>

{% endblock %}

catalog/templates/catalog/gensetengine_confirm_delete.html
{% extends "common/__l_single_col.html" %}
{% load staticfiles %}
{% block content %}

<div class = 'container'>
<br>
	<div class="row">
	<h2>Вы действительно хотите удалить эту марку?</h2>
		<br>
		<table class="table">
			<tbody>
				<tr>
					<th>Производитель двигателя ДГУ</th>
					<td>{{gensetengine.engine}}</td>
					
				</tr>
				<tr>
					<th>Логотип</th>
					<td>{{gensetengine.logo}}</td>
					
				</tr>
				<tr>
					<th>Текст ...</th>
					<td>{{gensetengine.text}}</td>
					
				</tr>
			</tbody>
		</table>
	</div>
	<div class="row">
		<div class="col-sm-2">
			<form action="" method="POST">
				{% csrf_token %}
				<input class="btn btn-warning" type="submit" action="" value="Да, удалить." />
			</form>
		</div>
		<div class="col-sm-2">
			<a class="btn btn-default" href="{% url 'catalog:gensetengine_list_corr' %}" role="button">Нет, оставить.</a>
		</div>
	</div>	
</div>
{% endblock %}

catalog/templates/catalog/gensetengine_form.html
{% extends "common/__l_single_col.html" %}

{% block content %}
<form  action="" method="post" enctype="multipart/form-data">
	<div class = 'container'>
		<h3>Данные о марке двигателя:</h3>

		<table class="table">
			<tbody>
			{% csrf_token %}
				<tr>
					<th>{{form.engine.label}}</th>
					<td>{{form.engine}}</td>
					{{form.engine.errors}}
				</tr>
				<tr>
					<th>{{form.logo.label}}</th>
					<td>{{form.logo}}</td>
					{{form.logo.errors}}
				</tr>
				<tr>
					<th>{{form.text.label}}</th>
					<td>{{form.text}}</td>
					{{form.text.errors}}
				</tr>
			</tbody>
		</table>
		<input class="btn btn-default" type="submit" value="СОХРАНИТЬ">
	</div>
</form>

{% endblock %}

catalog/templates/catalog/gensetengine_listcorr.html
{% extends "common/__l_single_col.html" %}
{% load staticfiles %}
{% block content %}

<div class = 'container'>
	<br>
	<div class="row">
		
		<div class="col-sm-3"><a class='certificate-menu' href="{% url 'catalog:genset_list' gensetengine_id %}" title="вернуться"><span class="glyphicon glyphicon-menu-left">вернуться</span></a>
		</div>

	</div>
	<br>	
	<table class='table catalog table-bordered '>
	<thead>
		<tr>
			<th class="invert">Удалить</th>
			<th class="invert">Править</th>
			<th>Марка</th>
			<th>Лого</th>
			<th>Текст на страницу ...</th>
		</tr>
	</thead>
   <tbody>
   {% if gensetengines %}
	   {% for gensetengine in gensetengines %}
		<tr>
		<td><a href="{% url 'catalog:gensetengine_delete' gensetengine.pk %}"><span class="glyphicon glyphicon-remove"></span></a></td>
		<td><a href="{% url 'catalog:gensetengine_update' gensetengine.pk %}"><span class="glyphicon glyphicon-pencil"></a></td>
		<td>{{gensetengine.engine}}</td>
		<td>{% if gensetengine.logo %}
		<img src="{{gensetengine.logo.url}}" class="img-thumbnail"alt='{{gensetengine.engine}} логотип'>
			{% endif %}</td>
		<td>{{gensetengine.text}}</td>
		</tr>
	   {% endfor %}
   {% endif %}
   </tbody>
   </table>

</div>
{% endblock %}

catalog/templates/catalog/gensetlist.html
{% extends "common/__l_single_col.html" %}
{% load staticfiles %}

{% block stylesheet %}
	{{ block.super }}
	<link rel="stylesheet" type="text/css" href="{% static 'css/responsive_catalog_table.css' %}">
{% endblock %}

{% block content %}

<div class = 'container'>

	<div class="row catalog-fill">
	<br>
		{% if user.is_authenticated %}
			{% if perms.company.add_genset %}
		<div class="col-sm-3"><a class='certificate-menu' href="{% url 'catalog:genset_create' gensetengine.pk %}" title="добавить дизельгенератор"><span class="glyphicon glyphicon-plus">добавить дизельгенератор</span></a>
		</div>
				{% if gensets|length %}
		<div class="col-sm-3"><a class='certificate-menu' href="{% url 'catalog:genset_list_corr' gensetengine.pk %}" title="редактировать таблицу"><span class="glyphicon glyphicon-remove"></span> <span class="glyphicon glyphicon-pencil">редактировать таблицу</span></a>
		</div>
				{% endif %}
			{% endif %}
		{% endif %}
	</div>
	<br>
	<div class="row">
		{% if gensetengine.logo %}
		<div class="col-md-1 col-sm-12 catalog-marka">
			<img class="img-responsive" src="{{gensetengine.logo.url}}">
		</div>

		{% endif %}

		<div class="col-md-11 col-sm-12 ">
			<h1 >{{gensetengine.engine|upper}}</h1>
		</div>
		
	</div>
	
<table class='table catalog table-bordered table-striped'>

	<thead>
		<tr>
			<th rowspan="2">МОДЕЛЬ<br>ДГУ</th>
			<th colspan="2">ESP(Stand-by)</th>
			<th colspan="2">PRP(Prime)</th>
			<th rowspan="2">МОДЕЛЬ<br>ДВИГАТЕЛЯ</th>
			<th rowspan="2 specification">СПЕЦИФИКАЦИЯ</th>
		</tr>
		<tr>
			<th>кВА</th>
			<th>кВ</th>
			<th>кВА</th>
			<th>кВ</th>
		</tr>
	</thead>
   

   <tbody>
   {% if gensets %}
	   {% for genset in gensets %}
		<tr>
			<td>{{genset.model}}</td>
			<td>{{genset.stand_by_kva}}</td>
			<td>{{genset.stand_by_kw}}</td>
			<td>{{genset.prime_kva}}</td>
			<td>{{genset.prime_kw}}</td>
			<td>{{genset.engine_model}}</td>

			<td>
			{% if genset.spec %}
				<a href="{{genset.spec.url}}">
					<img src="{% static 'images/get_pdf.jpg' %} " alt='получить спецификацию'>
				</a>
			{% else %}
			-
			{% endif %}
			</td>
		</tr>
	   {% endfor %}
   {% endif %}
   </tbody>
   </table>

</div>
{% endblock %}

catalog/templates/catalog/gensetlistcorr.html
{% extends "common/__l_single_col.html" %}
{% load staticfiles %}
{% block content %}

<div class = 'container'>
<br>
	<div class="row">
		{% if user.is_authenticated %}
			{% if perms.company.add_genset %}
		<div class="col-sm-3"><a class='certificate-menu' href="{% url 'catalog:genset_list' gensetengine.id %}" title="вернуться"><span class="glyphicon glyphicon-menu-left">вернуться</span></a>
		</div>
			{% endif %}
		{% endif %}
	</div>
	<br>
	<div class="row">
		{% if gensetengine.logo %}
		<div class="col-md-1 col-sm-12">
			<img class="img-responsive" src="{{gensetengine.logo.url}}">
		</div>
		{% endif %}

		<div class="col-md-11 col-sm-12">
			<h1 >{{gensetengine.engine|upper}}</h1>
		</div>
		
	</div>	
	<table class='table catalog table-bordered '>
  <tbody>
   <tr>
	<th class="invert" rowspan="2">Удалить</th>
	<th class="invert" rowspan="2">Править</th>
    <th rowspan="2">МОДЕЛЬ<br>ДГУ</th>
    <th colspan="2">ESP(Stand-by)</th>
    <th colspan="2">PRP(Prime)</th>
    <th rowspan="2">GOV</th>
    <th rowspan="2 specification">СПЕЦИФИКАЦИЯ</th>
   </tr>
   <tr>
		<th>кВА</th>
		<th>кВ</th>
		<th>кВА</th>
		<th>кВ</th>
   </tr>
   {% if gensets %}
	   {% for genset in gensets %}
		<tr>
		<td><a href="{% url 'catalog:genset_delete' genset.pk %}"><span class="glyphicon glyphicon-remove"></span></a></td>
		<td><a href="{% url 'catalog:genset_update' genset.pk %}"><span class="glyphicon glyphicon-pencil"></a></td>
		<td>{{genset.model}}</td>
		<td>{{genset.stand_by_kva}}</td>
		<td>{{genset.stand_by_kw}}</td>
		<td>{{genset.prime_kva}}</td>
		<td>{{genset.prime_kw}}</td>
		<td>{{genset.engine_model}}</td>
		<td>
		{% if genset.spec %}
		<a href="#"><img src="{% static 'images/get_pdf.jpg' %} " alt='получить спецификацию'></a></td>
		{% else %}
		-
		{% endif %}
		</tr>
	   {% endfor %}
   {% endif %}
   </tbody>
   </table>

</div>
{% endblock %}