energy_vector/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    url(r'^', include("main.urls")),
    url(r'^news/', include("news.urls")),
	url(r'^company/', include("company.urls")),
	url(r'^catalog/', include("catalog.urls")),
    url(r'^services/', include("services.urls")),
    url(r'^imagepool/', include("imagepool.urls")),

    url(r'^admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
# coding=utf-8
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'main'
urlpatterns = [

	url(r'^$', views.MainPageView.as_view(), name='main_page',),

	url(r'^call_order/$', views.CallorderFormView.as_view(),   name='call_order',),

	url(r'^order/(?P<serv_type>maintenance|repair)/(?P<equip_type>dgu|ups)/$',
						views.ServiceOrderFormView.as_view(),   name='service_order1',),

	url(r'^login/', auth_views.login,
		{"template_name":"end_templates/login.html"}, name='login'),
	url(r'^logout/', auth_views.logout, name='logout'),

]

services/urls.py
# coding=utf-8
from django.conf.urls import url
from . import views 


app_name = 'services'
urlpatterns = [
	
	# url(r'^send_request/$', views.send_request,   name='send_request')

	url(r'^(?P<pk>\d+)/$', views.ServiceDetailView.as_view(), 
						    	name='service_detail',),

	url(r'^create/$', views.ServiceCreate.as_view(), 
						    	name='service_create',),

	url(r'^(?P<pk>\d+)/update/$', views.ServiceUpdate.as_view(), 
						    	name='service_update',),

	url(r'^(?P<pk>\d+)/delete/$', views.ServiceDelete.as_view(), 
								name='service_delete',),
]

services/models.py
# coding=utf-8
from __future__ import unicode_literals

from django.db import models
from precise_bbcode.fields import BBCodeTextField

LINKS = (('/call_order/', 'ЗАКАЗАТЬ ЗВОНОК'),
		('/order/maintenance/dgu/', 'ЗАКАЗАТЬ ТЕХОБСЛУЖИВАНИЕ ДГУ'),
		('/order/maintenance/ups/', 'ЗАКАЗАТЬ ТЕХОБСЛУЖИВАНИЕ ИБП'),
		('/order/repair/dgu/','ЗАКАЗАТЬ РЕМОНТ ДГУ'),
		('/order/repair/ups/','ЗАКАЗАТЬ РЕМОНТ ИБП'),)
# Create your models here.
class Service(models.Model):
	serv_name = models.CharField(verbose_name = 'УСЛУГА', max_length=80, unique = True,)
	content = BBCodeTextField(verbose_name = 'ТЕКСТ ДЛЯ СТРАНИЦЫ УСЛУГИ',
								blank=True, null=True, default=None,)

	link = models.CharField(verbose_name = 'ЕСЛИ НУЖНО, ВЫБЕРИТЕ КНОПКУ НА ЗАКАЗ УСЛУГИ', max_length=30, 
								 blank=True, choices = LINKS,)
	

	def __unicode__(self):
		return self.serv_name

	def get_absolute_url(self):
		return u'/services/%d' % self.id 

services/views.py
# coding=utf-8
from django.shortcuts import render

from catalog.models import Gensetengine
from .models import Service


from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from generic.mixins import GensetengineListMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.urlresolvers import reverse_lazy
# Create your views here.


class ServiceDetailView(DetailView, GensetengineListMixin):
	model = Service


class ServiceCreate(PermissionRequiredMixin, CreateView, GensetengineListMixin):
	permission_required = 'service.can_add'
	model = Service
	fields = '__all__'
	context_object_name = 'services'	
	

class ServiceUpdate(PermissionRequiredMixin, UpdateView, GensetengineListMixin):
	permission_required = 'service.can_change'
	model = Service
	fields = '__all__'
	

class ServiceDelete(PermissionRequiredMixin, DeleteView, GensetengineListMixin):
	permission_required = 'service.can_delete'
	model = Service
	success_url = reverse_lazy('main:main_page')
	def get_context_data(self, **kwargs):
		context = super(ServiceDelete, self).get_context_data(**kwargs)
		context['back_url'] = '/services/'+ self.kwargs['pk']
		print "context['back_url']=",context
		return context

services/templates/services/call_order_form.html
{% extends "common/__l_single_col.html" %}
{% load bootstrap %}

{% block content %}    
    
<div class = 'my-form'>
  <div class="my-form-header">
    <a href="/" type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a>
    <h4 class="lead">ЗАКАЗАТЬ ОБРАТНЫЙ ЗВОНОК</h4>
  </div>
  <hr>

  <form  action='/send-email/' method='post'>
    {% csrf_token %}

    {{form|bootstrap}}    

    <div class="my-form-footer">
      <a href="/" type="button" class="btn btn-default" >ЗАКРЫТЬ</a>
      <button type="submit" class="btn btn-success">ЗАКАЗАТЬ ЗВОНОК</button>
    </div>
  </form>

</div>
{% endblock %}

services/templates/services/service_confirm_delete.html
{% extends "common/__l_single_col.html" %}
{% load staticfiles %}
{% block content %}

<div class = 'container'>
<br>
	<div class="row">
	<h2>Вы действительно хотите удалить эту услугу?</h2>
		<br>

	<div class="row">
		<div class="col-sm-2">
			<form action="" method="POST">
				{% csrf_token %}
				<input class="btn btn-warning" type="submit" action="" value="Да, удалить." />
			</form>
		</div>
		<div class="col-sm-2">
			<a class="btn btn-default" href="{{back_url}}" role="button">Нет, оставить.</a>
		</div>
	</div>	
</div>
{% endblock %}

services/templates/services/service_detail.html
{% extends "common/__l_single_col.html" %}
{% load bootstrap %}
{% block title %}
OOO "Вектор".{{service.name}}
{% endblock %}
{% block content %}
<div class = 'container'>
<div class="row catalog-fill">
	<br>
	{% if user.is_authenticated %}
		{% if perms.services.add_service %}
	<div class="col-sm-3"><a class='certificate-menu' href="{% url 'services:service_create' %}" title="добавить новую услугу"><span class="glyphicon glyphicon-plus">добавить новую услугу</span></a>
	</div>
			{% if services|length %}
	<div class="col-sm-3"><a class='certificate-menu' href="{% url 'services:service_update' service.id %}" title="редактировать список услуг"><span class="glyphicon glyphicon-pencil">редактировать страницу услуги</span></a>
	</div>
	<div class="col-sm-3"><a class='certificate-menu' href="{% url 'services:service_delete' service.id %}" title="редактировать список услуг"><span class="glyphicon glyphicon-remove">удалить услугу</span></a>
	</div>
			{% endif %}
		{% endif %}
	{% endif %}
</div>
<h3 class="text-success"><b>{{ service.serv_name }}</b></h3>
<hr>

<div class="service-content">{{ service.content.rendered }}</div>
<hr>
{% if service.link %}

<a href="{{service.link}}" type="button" class="btn btn-success" >{{service.get_link_display}}</a>
{% endif %}
</div>
{% endblock %}

services/templates/services/service_form.html
{% extends "common/__l_single_col.html" %}
{% load bootstrap %}
{% load staticfiles %}

{% block javascript %}
  {{ block.super }} 
  <script src="{% static "js/imagepool.js" %}" type="text/javascript"></script>
  
{% endblock %}

{% block content %}
<div class = 'container'>
  <div class="my-form-header">
    <a href="/" type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></a>
    <h4 class="lead">ДОБАВИТЬ/РЕДАКТИРОВАТЬ УСЛУГУ</h4>
  </div>
  <hr>
<form  action="" method="post" >
	
    {% csrf_token %}

    {{form|bootstrap}}   
	<div class="my-form-footer">
      <a href="/" type="button" class="btn btn-default" >ЗАКРЫТЬ</a>
      <button type="submit" class="btn btn-success">СОХРАНИТЬ</button>
    </div>
	
	
</form>
{% include "includes/_file_lister.html" %}
</div>
{% endblock %}